//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salita_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerService
    {
        public CustomerService()
        {
            this.CustomerNeeds = new HashSet<CustomerNeed>();
        }
    
        public int CustomerService_ID { get; set; }
        public string ServiceType { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CustomerNeed> CustomerNeeds { get; set; }
    }
}
