<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="default.aspx.cs" Inherits="Salita_Client._default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <meta name="viewport" content="width=768, initial-scale=1, maximum-scale=1, user-scalable=yes"/>
    <link href="css/jquery-ui.min.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ValidationSummary ID="ValidationSummary1" runat="server" />
    <asp:CustomValidator ID="CustomValidator1" runat="server" ErrorMessage="CustomValidator" Visible="false"></asp:CustomValidator>
    <canvas id="salitacanvas" width="768" height="995"></canvas>

    <div id="dialog-form" title="Servicios Complementarios">
        <p/>
        <fieldset>
            <label for="name">Commentarios</label>

            <textarea id="txtServiceNote" name="name" cols="1" rows="4" class="form-control"></textarea>

            <input type="submit" class="btn btn-primary" tabindex="-1" style="position:absolute; top:-1000px">
        </fieldset>
    </div>

    <div id="dialog-form-fulfill" title="Servicios Entregado">
        <p/>
        <fieldset>
            <label for="name">Commentarios</label>

            <textarea id="txtServiceNoteFulfillment" name="name" cols="1" rows="4" class="form-control"></textarea>

            <input type="submit" class="btn btn-primary" tabindex="-1" style="position:absolute; top:-1000px">
        </fieldset>
    </div>

    <!--
    <div id="dialog-form" title="Create new user">
        <p class="validateTips">All form fields are required.</p>
            <fieldset>
                <label for="name">Commentarios</label>

                <input type="text" name="name" id="name" value="Jane Smith" class="text ui-widget-content ui-corner-all">

                <label for="email">Email</label>

                <input type="text" name="email" id="email" value="jane@smith.com" class="text ui-widget-content ui-corner-all">

                <label for="password">Password</label>

                <input type="password" name="password" id="password" value="xxxxxxx" class="text ui-widget-content ui-corner-all">

                Allow form submission with keyboard without duplicating the dialog button

                <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
            </fieldset>
    </div>
    -->
    
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ScriptSection" runat="server">
    <script src="/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src="Scripts/moment.js"></script>
    <script src="Scripts/jquery-ui-1.11.4.min.js"></script>
    <script src="Scripts/salita.js" type="text/javascript"></script>
    <script type="text/javascript">
        init();

        dialog = $("#dialog-form").dialog({
            autoOpen: false,
            height: 300,
            width: 350,
            modal: true,
            buttons: {
                "Actualizar": addServiceToCustomer,
                Cancel: function () {
                    dialog.dialog("close");
                }
            },
            close: function ()
            {
                //form[0].reset();
                //allFields.removeClass("ui-state-error");
            }
        });

        dialog_Fulfill = $("#dialog-form-fulfill").dialog({
            autoOpen: false,
            height: 300,
            width: 350,
            modal: true,
            buttons: {
                "Actualizar": fulfillServiceToCustomer,
                Cancel: function () {
                    dialog_Fulfill.dialog("close");
                }
            },
            close: function () {
                //form[0].reset();
                //allFields.removeClass("ui-state-error");
            }
        });
    </script>

</asp:Content>