//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salita_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourSlot
    {
        public string HourSlotTime { get; set; }
        public Nullable<int> HourSlotOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
