//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salita_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int Map_ID { get; set; }
        public string MapName { get; set; }
        public string MapData { get; set; }
    }
}
