//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salita_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Visit_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> Seat_X { get; set; }
        public Nullable<int> Seat_Y { get; set; }
        public Nullable<bool> InLounge { get; set; }
        public string WaitingFor { get; set; }
        public string LoginPIN { get; set; }
        public string Mood { get; set; }
        public string AG_Phone { get; set; }
        public Nullable<int> AG_Companions { get; set; }
        public Nullable<bool> AG_LL { get; set; }
        public Nullable<bool> AG_RR { get; set; }
        public string AG_Tag { get; set; }
        public string AG_Advisor { get; set; }
        public string AG_DriveTo { get; set; }
        public string AG_AppointmentTime { get; set; }
        public string AG_AttendedTime { get; set; }
        public string AG_RegisteredTime { get; set; }
        public Nullable<bool> AG_OK { get; set; }
        public string AG_ExitTime { get; set; }
        public string AG_ArrivalTime { get; set; }
        public string AG_DriverName { get; set; }
        public string AG_Comments { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
