//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salita_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Visit_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> Seat_X { get; set; }
        public Nullable<int> Seat_Y { get; set; }
        public Nullable<bool> InLounge { get; set; }
        public string WaitingFor { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
